# Generated by Django 5.1.6 on 2025-04-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('turi', models.CharField(choices=[('oz', 'Oziq-ovqat'), ('kiyim', 'Kiyim-kechak'), ('elek', 'Elektronika'), ('boshqa', 'Boshqa')], max_length=10)),
                ('qoshimcha_malumot', models.TextField(blank=True)),
            ],
        ),
    ]
