# Generated by Django 5.1.6 on 2025-04-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='staticfiles/img'),
        ),
    ]
